version: '3.8'
services:
  priceservice:
    container_name: priceservice
    networks: 
      - backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

networks:
  backend: