spring:
  application:
    name: price-service
  datasource:
    url: jdbc:h2:mem:pricedb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

springdoc:
  api-docs:
    version: openapi-3-1
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: false
  group-configs:
    - group: prices
      paths-to-match: /**/prices/**