spring:
  application:
    name: price-service

springdoc:
  api-docs:
    version: openapi-3-1
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: false
  group-configs:
    - group: prices
      paths-to-match: /prices/**